POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.jingwei.rpc.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [1]
}

###
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "com.jingwei.rpc.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

###

